package ec.edu.espe.ms_clientes.model;

public enum ActividadType {
    AGRICULTURA, GANADERIA, PESCA, SILVICULTURA, MINERIA,
    CONSTRUCCION, COMERCIO, TRANSPORTE, EDUCACION, SANIDAD, FINANCIERO, TURISMO, MANUFACTURERA
}
